apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-project-deploy
  labels:
    app: banking-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-project
  template:
    metadata:
      labels:
        app: banking-project
    spec:
      containers:
      - name: banking-project-container
        image: vishweshrushi/banking_project:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: banking-project-np-svc
  labels:
    app: banking-project
spec:
  selector:
    app: banking-project

  type: NodePort
  ports:
  - nodePort: 30003  
    port: 8081
    targetPort: 8081